#!/bin/bash

_dbnav_log()
{
	echo $* >> /tmp/dbnav-complete.log
}
 
_dbnav_completer()
{
	local cur prev words
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"

	_dbnav_log "cur:${cur}, prev:${prev}"
	words="$(dbnav -a ${cur})"

	COMPREPLY=($(compgen -W "${words}" -- ${cur}))
	return 0
}

complete -o nospace -F _dbnav_completer dbnav

